initial_positions:
    home:
        base_link_to_base_plate: 0
        base_plate_to_arm_1: 0
        arm_1_to_arm_2: 0
        inner_circle_to_gripper_1: 0
        inner_circle_to_gripper_2: 0
        inner_circle_to_gripper_3: 0
