default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
    base_link_to_base_plate:
        has_velocity_limits: true
        max_velocity: 10.0
        has_acceleration_limits: false
        max_acceleration: 0.0

    base_plate_to_arm_1:
        has_velocity_limits: true
        max_velocity: 10.0
        has_acceleration_limits: false
        max_acceleration: 0.0
    arm_1_to_arm_2:
        has_velocity_limits: true
        max_velocity: 10.0
        has_acceleration_limits: false
        max_acceleration: 0.0
    inner_circle_to_gripper_1:
        has_velocity_limits: true
        max_velocity: 10.0
        has_acceleration_limits: false
        max_acceleration: 0.0
    inner_circle_to_gripper_2:
        has_velocity_limits: true
        max_velocity: 10.0
        has_acceleration_limits: false
        max_acceleration: 0.0
    inner_circle_to_gripper_3:
        has_velocity_limits: true
        max_velocity: 10.0
        has_acceleration_limits: false
        max_acceleration: 0.0
