moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

controller_names:
  - arm_controller
  - gripper_controller

arm_controller:
  type: FollowJointTrajectory
  joints:
    - base_link_to_base_plate
    - base_plate_to_arm_1
    - arm_1_to_arm_2
    - arm_2_to_arm_3
  action_ns: follow_joint_trajectory
  default: true

gripper_controller:
  type: FollowJointTrajectory
  joints:
    - gripper_support_to_inner_circle
  action_ns: follow_joint_trajectory
  default: true
