planning_scene_monitor_options:
  name: "planning_scene_monitor"
  robot_description: "robot_description"
  joint_state_topic: "/joint_states"
  attached_collision_object_topic: "/planning_scene_monitor"
  publish_planning_scene_topic: "/planning_scene"
  monitored_planning_scene_topic: "/planning_scene"
  wait_for_initial_state_timeout: 10.0

planning_pipelines:
  pipelines: [ompl, pilz_industrial_motion_planner] 