controller_manager:
  ros__parameters:
    update_rate: 10
    
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      #type: joint_trajectory_controller/JointTrajectoryController
      type: forward_command_controller/ForwardCommandController


arm_controller:
  ros__parameters:
    joints:
      - base_link_to_base_plate
      - base_plate_to_arm_1
      - arm_1_to_arm_2
      - arm_2_to_arm_3

    command_interfaces:
      - position
    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true

gripper_controller:
  ros__parameters:
    joints:
      - arm_2_to_inner_circle
      #- inner_circle_to_gripper_1
      #- inner_circle_to_gripper_2
      #- inner_circle_to_gripper_3

    interface_name: position
    # command_interfaces:
    #   - position
    #state_interfaces:
    #  - position
    # open_loop_control: true
    # allow_integration_in_goal_trajectories: true